FLASK DECORATORS EXAMPLE
Single call to Flask root endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:05.499727", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/", "traceId": "854a7fbec6f0c912f6745b514a2ae6ee", "spanID": "231d2786b123764e"}
{"severity": "INFO", "time": "2018-07-25T14:06:05.501335", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 23, "function": "wrapper"}, "message": "demoApp - 200 OK - http://localhost:5010/", "traceId": "854a7fbec6f0c912f6745b514a2ae6ee", "spanID": "231d2786b123764e"}
Done



Double call to Flask endpoints:
{"severity": "INFO", "time": "2018-07-25T14:06:05.514869", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/doublehttp", "traceId": "6ead450641c4c5b4d9279f056f1a7de0", "spanID": "119ad4666702c80a"}
{"severity": "INFO", "time": "2018-07-25T14:06:05.534044", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/", "traceId": "6ead450641c4c5b4d9279f056f1a7de0", "spanID": "119ad4666702c80a"}
{"severity": "INFO", "time": "2018-07-25T14:06:05.535285", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 23, "function": "wrapper"}, "message": "demoApp - 200 OK - http://localhost:5010/", "traceId": "6ead450641c4c5b4d9279f056f1a7de0", "spanID": "119ad4666702c80a"}
{"severity": "INFO", "time": "2018-07-25T14:06:05.541526", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 23, "function": "wrapper"}, "message": "demoApp - 200 OK - http://localhost:5010/doublehttp", "traceId": "6ead450641c4c5b4d9279f056f1a7de0", "spanID": "119ad4666702c80a"}
Done



Call to excluded endpoint:
Done



Call to handled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:05.564052", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/handledexception", "traceId": "303d497c12eb4658955e2ede4e25d640", "spanID": "861508e6472b4adc"}
{"severity": "ERROR", "time": "2018-07-25T14:06:05.565677", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 35, "function": "wrapper"}, "message": "demoApp - Exception: HandledException(This is a handled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py\", line 22, in wrapper\n    response, status_number = f(*args, **kwargs)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_decorators.py\", line 65, in handled_exception\n    raise HandledException('This is a handled Exception!')\n", "traceId": "303d497c12eb4658955e2ede4e25d640", "spanID": "861508e6472b4adc"}
{"severity": "ERROR", "time": "2018-07-25T14:06:05.569080", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 36, "function": "wrapper"}, "message": "demoApp - 500 INTERNAL SERVER ERROR - http://localhost:5010/handledexception", "traceId": "303d497c12eb4658955e2ede4e25d640", "spanID": "861508e6472b4adc"}
Call to unhandled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:05.581240", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/unhandledexception", "traceId": "80cac7dfed94aa2cfe3c4afb5a876e0f", "spanID": "ee1f83938fbac415"}
{"severity": "ERROR", "time": "2018-07-25T14:06:05.583242", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: UnhandledException(This is an unhandled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py\", line 22, in wrapper\n    response, status_number = f(*args, **kwargs)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_decorators.py\", line 71, in unhandled_exception\n    raise UnhandledException('This is an unhandled Exception!')\n", "traceId": "80cac7dfed94aa2cfe3c4afb5a876e0f", "spanID": "ee1f83938fbac415"}
Done






FLASK CALLBACKS EXAMPLE
Single call to Flask root endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:06.613325", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "traceId": "fde45939ac431b7e5191985ad9046296", "spanID": "646dffa10a2f61b8"}
{"severity": "INFO", "time": "2018-07-25T14:06:06.615311", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 36, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "traceId": "fde45939ac431b7e5191985ad9046296", "spanID": "646dffa10a2f61b8"}
Done



Double call to Flask endpoints:
{"severity": "INFO", "time": "2018-07-25T14:06:06.627543", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/doublehttp", "traceId": "181907b5ac706c1281f2454056d46269", "spanID": "43342212365eac68"}
{"severity": "INFO", "time": "2018-07-25T14:06:06.646381", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "traceId": "181907b5ac706c1281f2454056d46269", "spanID": "43342212365eac68"}
{"severity": "INFO", "time": "2018-07-25T14:06:06.648006", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 36, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "traceId": "181907b5ac706c1281f2454056d46269", "spanID": "43342212365eac68"}
{"severity": "INFO", "time": "2018-07-25T14:06:06.654313", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 36, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/doublehttp", "traceId": "181907b5ac706c1281f2454056d46269", "spanID": "43342212365eac68"}
Done



Two calls to excluded endpoints:
Done



Call to handled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:06.686150", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/handledexception", "traceId": "8ee12a4d59e9546be4cbec7cf1f12e98", "spanID": "cbdb95e432950462"}
{"severity": "ERROR", "time": "2018-07-25T14:06:06.690406", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 50, "function": "wrapper"}, "message": "demoApp - Exception: HandledException(This is a handled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_callbacks.py\", line 76, in handled_exception\n    raise HandledException('This is a handled Exception!')\n", "traceId": "8ee12a4d59e9546be4cbec7cf1f12e98", "spanID": "cbdb95e432950462"}
{"severity": "ERROR", "time": "2018-07-25T14:06:06.692409", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 500 INTERNAL SERVER ERROR - http://localhost:5005/handledexception", "traceId": "8ee12a4d59e9546be4cbec7cf1f12e98", "spanID": "cbdb95e432950462"}
Call to unhandled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:06.703676", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/unhandledexception", "traceId": "ed3bed73db51c3a2c6d17ef730328f9b", "spanID": "72f6f0cdc6a4f390"}
{"severity": "ERROR", "time": "2018-07-25T14:06:06.705335", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: UnhandledException(This is an unhandled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_callbacks.py\", line 81, in unhandled_exception\n    raise UnhandledException('This is an unhandled Exception!')\n", "traceId": "ed3bed73db51c3a2c6d17ef730328f9b", "spanID": "72f6f0cdc6a4f390"}
Done






GRPC EXAMPLE
Call to gRPC endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:07.721031", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPC': {}", "traceId": "4648cbe1b507033344bd95025c0d2a10", "spanID": "dcb9168c5a9a776f"}
{"severity": "INFO", "time": "2018-07-25T14:06:07.721779", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 53, "function": "log_span"}, "message": "demoApp - gRPC - Return 'DemoRPC'", "traceId": "4648cbe1b507033344bd95025c0d2a10", "spanID": "dcb9168c5a9a776f"}



Call to handled exception endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:07.725566", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPCHandledException': {}", "traceId": "f59547432708ef6a7d48b3ce7f3b6d3c", "spanID": "e604ba892379f08e"}
{"severity": "ERROR", "time": "2018-07-25T14:06:07.725935", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 49, "function": "log_span"}, "message": "demoApp - Exception: HandledException(This is a handled exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 47, in log_span\n    response = f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 53, in DemoRPCHandledException\n    raise HandledException('This is a handled exception!')\n", "traceId": "f59547432708ef6a7d48b3ce7f3b6d3c", "spanID": "e604ba892379f08e"}
{"severity": "ERROR", "time": "2018-07-25T14:06:07.727470", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 50, "function": "log_span"}, "message": "demoApp - gRPC - HandledException - 'DemoRPCHandledException'", "traceId": "f59547432708ef6a7d48b3ce7f3b6d3c", "spanID": "e604ba892379f08e"}
StatusCode.INTERNAL Handled exception, closing context



Call to unhandled exception endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:07.731230", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPCUnHandledException': {}", "traceId": "481e7a03b1a23b6234b2ad398bbb4770", "spanID": "115119d6a2bf7fdf"}
{"severity": "ERROR", "time": "2018-07-25T14:06:07.731932", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 49, "function": "log_span"}, "message": "demoApp - Exception: UnhandledException(This is an unhandled exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 47, in log_span\n    response = f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 56, in DemoRPCUnHandledException\n    raise UnhandledException('This is an unhandled exception!')\n", "traceId": "481e7a03b1a23b6234b2ad398bbb4770", "spanID": "115119d6a2bf7fdf"}
{"severity": "ERROR", "time": "2018-07-25T14:06:07.733034", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 50, "function": "log_span"}, "message": "demoApp - gRPC - UnhandledException - 'DemoRPCUnHandledException'", "traceId": "481e7a03b1a23b6234b2ad398bbb4770", "spanID": "115119d6a2bf7fdf"}
{"severity": "ERROR", "time": "2018-07-25T14:06:07.733697", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/grpc/_server.py", "line": 397, "function": "_call_behavior"}, "message": "grpc._server - Exception: UnhandledException(This is an unhandled exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/grpc/_server.py\", line 389, in _call_behavior\n    return behavior(argument, context), True\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 27, in wrapper\n    return f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 52, in log_span\n    raise e\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 47, in log_span\n    response = f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 56, in DemoRPCUnHandledException\n    raise UnhandledException('This is an unhandled exception!')\n"}
StatusCode.UNKNOWN Exception calling application: This is an unhandled exception!



Call to endpoint with redacted values:
{"severity": "INFO", "time": "2018-07-25T14:06:07.741624", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPCRedactedParameters': value1: \"REDACTED\"\nvalue2: \"2\"\nnested {\n  nestedvalue1: \"REDACTED\"\n  nestedvalue2: \"2\"\n  doublenested {\n    doublenestedvalue1: \"REDACTED\"\n    doublenestedvalue2: \"2\"\n  }\n}\n", "traceId": "72794a2217b165497445952e4c561fae", "spanID": "21dc19fea89a72e1"}
{"severity": "INFO", "time": "2018-07-25T14:06:07.742376", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 53, "function": "log_span"}, "message": "demoApp - gRPC - Return 'DemoRPCRedactedParameters'", "traceId": "72794a2217b165497445952e4c561fae", "spanID": "21dc19fea89a72e1"}



Call to Flask endpoint that calls gRPC endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:07.752936", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/grpc", "traceId": "30db9aa5b0b18daa834efd8007a3a866", "spanID": "f3c2af3c6f6b1e8c"}
{"severity": "ERROR", "time": "2018-07-25T14:06:07.754429", "sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: TypeError(None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>))\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_callbacks.py\", line 44, in grpc\n    b3_values=generate_new_traced_subspan_values()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py\", line 499, in init\n    copy.update(field_value)\n\n  File \"/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_collections_abc.py\", line 841, in update\n    self[key] = other[key]\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/google/protobuf/internal/containers.py\", line 487, in __setitem__\n    checked_value = self._value_checker.CheckValue(value)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/google/protobuf/internal/type_checkers.py\", line 177, in CheckValue\n    raise TypeError(message)\n", "traceId": "30db9aa5b0b18daa834efd8007a3a866", "spanID": "f3c2af3c6f6b1e8c"}
Done
****** GCP formatted examples with posted traces ******






FLASK DECORATORS EXAMPLE
Single call to Flask root endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:08.781791", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/55a15aec84bc98c84620a61201cd357d", "logging.googleapis.com/spanId": "71f49ee8627ebf11"}
{"severity": "INFO", "time": "2018-07-25T14:06:08.783265", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 23, "function": "wrapper"}, "message": "demoApp - 200 OK - http://localhost:5010/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/55a15aec84bc98c84620a61201cd357d", "logging.googleapis.com/spanId": "71f49ee8627ebf11"}
Done



Double call to Flask endpoints:
{"severity": "INFO", "time": "2018-07-25T14:06:08.800200", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/doublehttp", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/3cdc909bc055bf73650ea21670cee795", "logging.googleapis.com/spanId": "99da486bac4b763e"}
{"severity": "INFO", "time": "2018-07-25T14:06:08.818999", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/3cdc909bc055bf73650ea21670cee795", "logging.googleapis.com/spanId": "99da486bac4b763e"}
{"severity": "INFO", "time": "2018-07-25T14:06:08.820248", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 23, "function": "wrapper"}, "message": "demoApp - 200 OK - http://localhost:5010/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/3cdc909bc055bf73650ea21670cee795", "logging.googleapis.com/spanId": "99da486bac4b763e"}
{"severity": "INFO", "time": "2018-07-25T14:06:08.828718", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 23, "function": "wrapper"}, "message": "demoApp - 200 OK - http://localhost:5010/doublehttp", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/3cdc909bc055bf73650ea21670cee795", "logging.googleapis.com/spanId": "99da486bac4b763e"}
Done



Call to excluded endpoint:
Done



Call to handled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:08.884920", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/handledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/940fedd608a84af63771e44a723c498d", "logging.googleapis.com/spanId": "fd41a554fe80b938"}
{"severity": "ERROR", "time": "2018-07-25T14:06:08.886468", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 35, "function": "wrapper"}, "message": "demoApp - Exception: HandledException(This is a handled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py\", line 22, in wrapper\n    response, status_number = f(*args, **kwargs)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_decorators.py\", line 65, in handled_exception\n    raise HandledException('This is a handled Exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/940fedd608a84af63771e44a723c498d", "logging.googleapis.com/spanId": "fd41a554fe80b938"}
{"severity": "ERROR", "time": "2018-07-25T14:06:08.887910", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 36, "function": "wrapper"}, "message": "demoApp - 500 INTERNAL SERVER ERROR - http://localhost:5010/handledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/940fedd608a84af63771e44a723c498d", "logging.googleapis.com/spanId": "fd41a554fe80b938"}
Call to unhandled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:08.914205", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 21, "function": "wrapper"}, "message": "demoApp - GET - http://localhost:5010/unhandledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/50e2e1072c823719eeb3bd92cc899ed8", "logging.googleapis.com/spanId": "13a652d8232df054"}
{"severity": "ERROR", "time": "2018-07-25T14:06:08.915309", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: UnhandledException(This is an unhandled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py\", line 22, in wrapper\n    response, status_number = f(*args, **kwargs)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_decorators.py\", line 71, in unhandled_exception\n    raise UnhandledException('This is an unhandled Exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/50e2e1072c823719eeb3bd92cc899ed8", "logging.googleapis.com/spanId": "13a652d8232df054"}
Done






FLASK CALLBACKS EXAMPLE
Single call to Flask root endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:09.949433", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/89f78ff01d84e130a43f2461dddb996f", "logging.googleapis.com/spanId": "d259b23ab3d81bdd"}
{"severity": "INFO", "time": "2018-07-25T14:06:09.951399", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 36, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/89f78ff01d84e130a43f2461dddb996f", "logging.googleapis.com/spanId": "d259b23ab3d81bdd"}
Done



Double call to Flask endpoints:
{"severity": "INFO", "time": "2018-07-25T14:06:09.966662", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/doublehttp", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/236753b82dc162d556b19c22f8cbcf49", "logging.googleapis.com/spanId": "a412f045d38c1b42"}
{"severity": "INFO", "time": "2018-07-25T14:06:09.983756", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/236753b82dc162d556b19c22f8cbcf49", "logging.googleapis.com/spanId": "a412f045d38c1b42"}
{"severity": "INFO", "time": "2018-07-25T14:06:09.985282", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 36, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/236753b82dc162d556b19c22f8cbcf49", "logging.googleapis.com/spanId": "a412f045d38c1b42"}
{"severity": "INFO", "time": "2018-07-25T14:06:09.994461", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 36, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/doublehttp", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/236753b82dc162d556b19c22f8cbcf49", "logging.googleapis.com/spanId": "a412f045d38c1b42"}
Done



Two calls to excluded endpoints:
Done



Call to handled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:10.029327", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/handledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/c44ca8fd7452e0e33ec6079a504ed89d", "logging.googleapis.com/spanId": "be93d541240c7783"}
{"severity": "ERROR", "time": "2018-07-25T14:06:10.031063", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/decorators.py", "line": 50, "function": "wrapper"}, "message": "demoApp - Exception: HandledException(This is a handled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_callbacks.py\", line 76, in handled_exception\n    raise HandledException('This is a handled Exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/c44ca8fd7452e0e33ec6079a504ed89d", "logging.googleapis.com/spanId": "be93d541240c7783"}
{"severity": "ERROR", "time": "2018-07-25T14:06:10.032922", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 500 INTERNAL SERVER ERROR - http://localhost:5005/handledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/c44ca8fd7452e0e33ec6079a504ed89d", "logging.googleapis.com/spanId": "be93d541240c7783"}
Call to unhandled exception:
{"severity": "INFO", "time": "2018-07-25T14:06:10.048821", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/unhandledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/b2041f5b22aa277ce24bd3770ea42177", "logging.googleapis.com/spanId": "1f52148ca4a911cc"}
{"severity": "ERROR", "time": "2018-07-25T14:06:10.049935", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: UnhandledException(This is an unhandled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_callbacks.py\", line 81, in unhandled_exception\n    raise UnhandledException('This is an unhandled Exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/b2041f5b22aa277ce24bd3770ea42177", "logging.googleapis.com/spanId": "1f52148ca4a911cc"}
Done






GRPC EXAMPLE
Call to gRPC endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:11.065727", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPC': {}", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/155434f843afac327aa55f6c2d025af8", "logging.googleapis.com/spanId": "918781f1c176ebd8"}
{"severity": "INFO", "time": "2018-07-25T14:06:11.066635", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 53, "function": "log_span"}, "message": "demoApp - gRPC - Return 'DemoRPC'", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/155434f843afac327aa55f6c2d025af8", "logging.googleapis.com/spanId": "918781f1c176ebd8"}



Call to handled exception endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:11.078678", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPCHandledException': {}", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/169a7af343d656d7a3225f014946da5f", "logging.googleapis.com/spanId": "1d3f5aa281017ab6"}
{"severity": "ERROR", "time": "2018-07-25T14:06:11.079786", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 49, "function": "log_span"}, "message": "demoApp - Exception: HandledException(This is a handled exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 47, in log_span\n    response = f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 53, in DemoRPCHandledException\n    raise HandledException('This is a handled exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/169a7af343d656d7a3225f014946da5f", "logging.googleapis.com/spanId": "1d3f5aa281017ab6"}
{"severity": "ERROR", "time": "2018-07-25T14:06:11.080989", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 50, "function": "log_span"}, "message": "demoApp - gRPC - HandledException - 'DemoRPCHandledException'", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/169a7af343d656d7a3225f014946da5f", "logging.googleapis.com/spanId": "1d3f5aa281017ab6"}
StatusCode.INTERNAL Handled exception, closing context



Call to unhandled exception endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:11.086844", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPCUnHandledException': {}", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/9f2c2e472c2e2778e3bc4fac97e612e3", "logging.googleapis.com/spanId": "0ee4d58a7eb6fb42"}
{"severity": "ERROR", "time": "2018-07-25T14:06:11.087247", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 49, "function": "log_span"}, "message": "demoApp - Exception: UnhandledException(This is an unhandled exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 47, in log_span\n    response = f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 56, in DemoRPCUnHandledException\n    raise UnhandledException('This is an unhandled exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/9f2c2e472c2e2778e3bc4fac97e612e3", "logging.googleapis.com/spanId": "0ee4d58a7eb6fb42"}
{"severity": "ERROR", "time": "2018-07-25T14:06:11.088284", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 50, "function": "log_span"}, "message": "demoApp - gRPC - UnhandledException - 'DemoRPCUnHandledException'", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/9f2c2e472c2e2778e3bc4fac97e612e3", "logging.googleapis.com/spanId": "0ee4d58a7eb6fb42"}
{"severity": "ERROR", "time": "2018-07-25T14:06:11.091717", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/grpc/_server.py", "line": 397, "function": "_call_behavior"}, "message": "grpc._server - Exception: UnhandledException(This is an unhandled exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/grpc/_server.py\", line 389, in _call_behavior\n    return behavior(argument, context), True\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 27, in wrapper\n    return f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 52, in log_span\n    raise e\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py\", line 47, in log_span\n    response = f(self, request, context)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/grpc_server.py\", line 56, in DemoRPCUnHandledException\n    raise UnhandledException('This is an unhandled exception!')\n"}
StatusCode.UNKNOWN Exception calling application: This is an unhandled exception!



Call to endpoint with redacted values:
{"severity": "INFO", "time": "2018-07-25T14:06:11.098376", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 43, "function": "log_span"}, "message": "demoApp - gRPC - Call 'DemoRPCRedactedParameters': value1: \"REDACTED\"\nvalue2: \"2\"\nnested {\n  nestedvalue1: \"REDACTED\"\n  nestedvalue2: \"2\"\n  doublenested {\n    doublenestedvalue1: \"REDACTED\"\n    doublenestedvalue2: \"2\"\n  }\n}\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/b197b59a7124907bc178230e7f77dfb3", "logging.googleapis.com/spanId": "9c20b4f89da9cd6d"}
{"severity": "INFO", "time": "2018-07-25T14:06:11.099067", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/grpc_helpers/decorators.py", "line": 53, "function": "log_span"}, "message": "demoApp - gRPC - Return 'DemoRPCRedactedParameters'", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/b197b59a7124907bc178230e7f77dfb3", "logging.googleapis.com/spanId": "9c20b4f89da9cd6d"}



Call to Flask endpoint that calls gRPC endpoint:
{"severity": "INFO", "time": "2018-07-25T14:06:11.111912", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/stackdriver_logging/flask_helpers/callbacks.py", "line": 17, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/grpc", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/197b6487ccaa4764b32edcef468be4f0", "logging.googleapis.com/spanId": "299c4a179f9d6c97"}
{"severity": "ERROR", "time": "2018-07-25T14:06:11.113538", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: TypeError(None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>))\nTraceback:\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/examples/flask_server_callbacks.py\", line 44, in grpc\n    b3_values=generate_new_traced_subspan_values()\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py\", line 499, in init\n    copy.update(field_value)\n\n  File \"/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_collections_abc.py\", line 841, in update\n    self[key] = other[key]\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/google/protobuf/internal/containers.py\", line 487, in __setitem__\n    checked_value = self._value_checker.CheckValue(value)\n\n  File \"/Users/windet01/Files/Code/stackdriver_logging/venv/lib/python3.7/site-packages/google/protobuf/internal/type_checkers.py\", line 177, in CheckValue\n    raise TypeError(message)\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/197b6487ccaa4764b32edcef468be4f0", "logging.googleapis.com/spanId": "299c4a179f9d6c97"}
Done